### ISSUE TITLE
Clicking on the Select Visualisation drop down arrow on Module AND Student Overviews takes you home

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#160]
since referenced in https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/294

whereas it should just open/close the drop down menu and stay on the same page. Error observed in Chrome on x-dev 0.12.1

![screen shot 2017-07-25 at 17 02 39](https://user-images.githubusercontent.com/1846710/28581850-5fa8fcea-715b-11e7-8859-a9580876b971.png)

**Comment by pdiveris** [comment]
OK this happened in both Student and Module Overview pages as it was a problem with the "Select Visualisation" menu entry. I have fixed this now in 0.13, committed, pushed and released on staging. Dev is 0.12.1 so I will be be releasing at the end of play today when I backport all today's fixes.

**Comment by robbristow-jisc** [comment]
Ok - that seems to be gone on the Select Visualisation drop down, but still happens on the Graph Type drop down on the Module Overview screen

**Comment by michaelwebbjisc** [comment]
Confirmed fixed.
